//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMHRD.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OMHRDModel : DbContext
    {
        public OMHRDModel()
            : base("name=OMHRDModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_T> Address_T { get; set; }
        public virtual DbSet<AddressState_T> AddressState_T { get; set; }
        public virtual DbSet<BankAccount_T> BankAccount_T { get; set; }
        public virtual DbSet<Cart_T> Cart_T { get; set; }
        public virtual DbSet<Nominee_T> Nominee_T { get; set; }
        public virtual DbSet<Order_T> Order_T { get; set; }
        public virtual DbSet<OrderPayment_T> OrderPayment_T { get; set; }
        public virtual DbSet<OrderProduct_T> OrderProduct_T { get; set; }
        public virtual DbSet<Product_T> Product_T { get; set; }
        public virtual DbSet<ProductCategory_T> ProductCategory_T { get; set; }
        public virtual DbSet<ProductColor_T> ProductColor_T { get; set; }
        public virtual DbSet<ProductPrice_T> ProductPrice_T { get; set; }
        public virtual DbSet<ProductSize_T> ProductSize_T { get; set; }
        public virtual DbSet<ProductSubCategory_T> ProductSubCategory_T { get; set; }
        public virtual DbSet<UserDocument_T> UserDocument_T { get; set; }
        public virtual DbSet<UserProfile_T> UserProfile_T { get; set; }
    }
}
