//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMHRD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment_T
    {
        public int Id { get; set; }
        public string Txn { get; set; }
        public System.DateTime TxnDatetime { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMode { get; set; }
        public string Status { get; set; }
        public int OrderId { get; set; }
        public string FailureMessage { get; set; }
    
        public virtual Order_T Order_T { get; set; }
    }
}
