//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMHRD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile_T()
        {
            this.Address_T = new HashSet<Address_T>();
            this.BankAccount_T = new HashSet<BankAccount_T>();
            this.Cart_T = new HashSet<Cart_T>();
            this.Nominee_T = new HashSet<Nominee_T>();
            this.Order_T = new HashSet<Order_T>();
            this.UserDocument_T = new HashSet<UserDocument_T>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ContactNo { get; set; }
        public string ReferenceBy { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string CompanyName { get; set; }
        public string IdentificationType { get; set; }
        public string TexExempt { get; set; }
        public string WFile { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<System.DateTime> SmartDeliveryDate { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public string CoApplicant { get; set; }
        public string Language { get; set; }
        public string Skype { get; set; }
        public string Teitter { get; set; }
        public string Facebook { get; set; }
        public byte[] PhotoImage { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserParentId { get; set; }
        public Nullable<decimal> WalletBalance { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<bool> IsSpecialUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address_T> Address_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount_T> BankAccount_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_T> Cart_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nominee_T> Nominee_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_T> Order_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDocument_T> UserDocument_T { get; set; }
    }
}
